import { GalleryPreset } from '@/types/gallery-theme';

export const MODEL_REGISTRY_KEYS = [
  'BenchA',
  'CoralA',
  'CoralB',
  'CoralC',
  'CrystalA',
  'FishA',
  'FishB',
  'FlowerA',
  'FlowerB',
  'FlowerC',
  'RockA',
  'RockB',
  'RocketA',
  'RocketB',
  'StarA',
  'TreeA',
  'TreeB',
  'TreeC',
  'PresentACube',
  'PresentARound',
  'PresentBCube',
  'PresentBRound',
  'SnowPile',
  'TreeDecoratedSnow',
  'WreathDecorated',
  'FlowerTreeA',
  'FlowerTreeB',
  'TreeD',
  'TreeE',
] as const;

export const defaultPreset: GalleryPreset = {
  id: 'default',
  atmosphere: {
    type: 'sky',
    sunPosition: [20, 15, 25],
    turbidity: 8,
    rayleigh: 1.8,
    mieCoefficient: 0.004,
    mieDirectionalG: 0.88,
    clouds: true,
  },
  lighting: {
    hemisphere: ['#FFD0A0', '#C8A080', 0.5],
    ambient: { color: '#FFF5EE', intensity: 0.9 },
    directional: {
      position: [20, 20, 25],
      color: '#FFB060',
      intensity: 1.6,
    },
    toneMappingExposure: 1.5,
  },
  floor: {
    color: '#ffffff',
    roughness: 0.7,
    metalness: 0.05,
    mirror: 0,
    blur: [300, 100],
    useTexture: true,
  },
  wallColor: '#ffffff',
  decorations: [],
};

export const christmasPreset: GalleryPreset = {
  id: 'christmas',
  atmosphere: {
    type: 'night',
    bgColor: '#03060f',
    stars: {
      radius: 120,
      depth: 60,
      count: 6000,
      factor: 5,
      saturation: 0.3,
      speed: 0.6,
    },
  },
  lighting: {
    hemisphere: ['#1a2a50', '#0d1530', 0.8],
    ambient: { color: '#c8d8ff', intensity: 0.55 },
    directional: {
      position: [-20, 35, -25],
      color: '#8aaae0',
      intensity: 0.7,
    },
    toneMappingExposure: 1.1,
  },
  floor: {
    color: '#d4eeff',
    roughness: 0.5,
    metalness: 0.0,
    mirror: 0.15,
    blur: [1000, 500],
    useTexture: false,
  },
  wallColor: '#d4eeff',
  decorations: [
    {
      model: 'TreeDecoratedSnow',
      count: 4,
      placement: 'corner',
      scaleMin: 0.8,
      scaleMax: 0.8,
    },
    {
      model: 'SnowPile',
      count: 4,
      placement: 'scattered',
      scaleMin: 0.5,
      scaleMax: 3.0,
    },
    {
      model: 'PresentACube',
      count: 8,
      placement: 'scattered',
      scaleMin: 0.22,
      scaleMax: 0.45,
    },
  ],
  particles: {
    type: 'snow',
    color: '#b8d8ff',
    count: 60,
    speed: 1.5,
    opacity: 0.55,
  },
};

export const aiPresetSpace: GalleryPreset = {
  id: 'space-adventure',
  atmosphere: {
    type: 'night',
    bgColor: '#050a14',
    stars: {
      radius: 100,
      depth: 50,
      count: 5000,
      factor: 4,
      saturation: 0.5,
      speed: 0.5,
    },
  },
  lighting: {
    hemisphere: ['#6060cc', '#303060', 1.0],
    ambient: { color: '#c0c0ff', intensity: 2.0 },
    directional: { position: [5, 10, 5], color: '#ffffff', intensity: 2.2 },
    toneMappingExposure: 1.7,
  },
  floor: {
    color: '#0d0d1a',
    roughness: 0.2,
    metalness: 0.15,
    mirror: 0.5,
    blur: [800, 400],
    useTexture: false,
  },
  wallColor: '#0d0d1a',
  decorations: [
    {
      model: 'RocketA',
      count: 2,
      placement: 'cell-center',
      scaleMin: 0.8,
      scaleMax: 1.2,
      color: '#cc4422',
      elevationMin: 2.0,
      elevationMax: 4.5,
    },
    {
      model: 'RocketB',
      count: 2,
      placement: 'cell-center',
      scaleMin: 0.7,
      scaleMax: 1.1,
      color: '#7733cc',
      elevationMin: 1.8,
      elevationMax: 4.0,
    },
    {
      model: 'StarA',
      count: 8,
      placement: 'scattered',
      scaleMin: 0.5,
      scaleMax: 1.0,
      color: '#ffd700',
      elevationMin: 1.0,
      elevationMax: 3.5,
    },
    {
      model: 'CrystalA',
      count: 4,
      placement: 'corner',
      scaleMin: 0.8,
      scaleMax: 1.3,
      color: '#4488ff',
    },
  ],
  particles: {
    type: 'sparkles',
    color: '#aaccff',
    count: 80,
    speed: 0.15,
    opacity: 0.5,
  },
};
export const aiPresetVoyage: GalleryPreset = {
  id: 'underwater-adventure',
  atmosphere: {
    type: 'gradient',
    topColor: '#1a6fa8',
    bottomColor: '#0a3d62',
  },
  lighting: {
    hemisphere: ['#40a8d8', '#1a5a8a', 1.0],
    ambient: { color: '#80c8f0', intensity: 1.3 },
    directional: { position: [2, 6, 2], color: '#a0d8f8', intensity: 1.6 },
    toneMappingExposure: 1.4,
  },
  floor: {
    color: '#0a3d62',
    roughness: 0.3,
    metalness: 0.1,
    mirror: 0.4,
    blur: [600, 200],
    useTexture: false,
  },
  wallColor: '#a0d4f0',
  decorations: [
    {
      model: 'CoralA',
      count: 8,
      placement: 'scattered',
      scaleMin: 0.6,
      scaleMax: 1.4,
      color: '#ff6b6b',
    },
    {
      model: 'CoralB',
      count: 7,
      placement: 'scattered',
      scaleMin: 0.5,
      scaleMax: 1.2,
      color: '#cc44aa',
    },
    {
      model: 'FishA',
      count: 8,
      placement: 'scattered',
      scaleMin: 0.5,
      scaleMax: 1.0,
      color: '#ffaa22',
      elevationMin: 1.5,
      elevationMax: 4.5,
    },
    {
      model: 'FishB',
      count: 7,
      placement: 'scattered',
      scaleMin: 0.4,
      scaleMax: 1.2,
      color: '#44ddaa',
      elevationMin: 2.0,
      elevationMax: 5.0,
    },
  ],
  particles: {
    type: 'sparkles',
    color: '#a0e8ff',
    count: 70,
    speed: 0.15,
    opacity: 0.4,
  },
};

export const aiPresetBlossom: GalleryPreset = {
  id: 'spring-blossom',
  atmosphere: {
    type: 'sky',
    sunPosition: [1, 1.2, 0.5],
    turbidity: 3,
    rayleigh: 0.7,
    mieCoefficient: 0.003,
    mieDirectionalG: 0.75,
    clouds: true,
  },
  lighting: {
    hemisphere: ['#ffccdd', '#c8f0c0', 0.9],
    ambient: { color: '#ffd6e8', intensity: 1.4 },
    directional: { position: [3, 5, 2], color: '#fff8f0', intensity: 1.8 },
    toneMappingExposure: 1.3,
  },
  floor: {
    color: '#fff5f8',
    roughness: 0.65,
    metalness: 0.03,
    mirror: 0.08,
    blur: [300, 100],
    useTexture: true,
  },
  wallColor: '#fff0f5',
  decorations: [
    {
      model: 'FlowerTreeA',
      count: 2,
      placement: 'cell-center',
      scaleMin: 0.9,
      scaleMax: 1.6,
      color: '#ff85b3',
    },
    {
      model: 'FlowerTreeB',
      count: 2,
      placement: 'cell-center',
      scaleMin: 0.8,
      scaleMax: 1.4,
      color: '#ff9ec7',
    },
    {
      model: 'FlowerB',
      count: 8,
      placement: 'scattered',
      scaleMin: 0.5,
      scaleMax: 1.0,
      color: '#ffaad4',
    },
    {
      model: 'BenchA',
      count: 3,
      placement: 'scattered',
      scaleMin: 0.7,
      scaleMax: 1.0,
      color: '#c8a97e',
    },
  ],
  particles: {
    type: 'petals',
    color: '#ffb3d9',
    count: 60,
    speed: 1.1,
    opacity: 0.85,
  },
};
export const aiPresetWinter: GalleryPreset = {
  id: 'winter-snowday',
  atmosphere: {
    type: 'night',
    bgColor: '#0a1628',
    stars: {
      radius: 100,
      depth: 50,
      count: 3000,
      factor: 4,
      saturation: 0.3,
      speed: 0.5,
    },
  },
  lighting: {
    hemisphere: ['#c8deff', '#8aaed4', 0.8],
    ambient: { color: '#b0c8e8', intensity: 1.5 },
    directional: { position: [2, 5, 3], color: '#ddeeff', intensity: 2.0 },
    toneMappingExposure: 1.6,
  },
  floor: {
    color: '#d4eeff',
    roughness: 0.5,
    metalness: 0.0,
    mirror: 0.15,
    blur: [1000, 500],
    useTexture: false,
  },
  wallColor: '#e8f4ff',
  decorations: [
    {
      model: 'TreeDecoratedSnow',
      count: 4,
      placement: 'cell-center',
      scaleMin: 0.8,
      scaleMax: 1.2,
      color: '#c8e0f0',
    },
    {
      model: 'SnowPile',
      count: 8,
      placement: 'scattered',
      scaleMin: 0.5,
      scaleMax: 2.0,
      color: '#e8f4ff',
    },
    {
      model: 'PresentACube',
      count: 5,
      placement: 'scattered',
      scaleMin: 0.25,
      scaleMax: 0.45,
      color: '#ff8fa3',
    },
    {
      model: 'PresentBRound',
      count: 4,
      placement: 'scattered',
      scaleMin: 0.22,
      scaleMax: 0.4,
      color: '#80c8ff',
    },
  ],
  particles: {
    type: 'snow',
    color: '#e8f4ff',
    count: 65,
    speed: 5,
    opacity: 0.8,
  },
};
export const aiPresetRainy: GalleryPreset = {
  id: 'rainy-day-puddles',
  atmosphere: {
    type: 'gradient',
    topColor: '#4a5568',
    bottomColor: '#2d3748',
  },
  lighting: {
    hemisphere: ['#7a8fa8', '#4a5a6a', 0.7],
    ambient: { color: '#98aabb', intensity: 1.2 },
    directional: { position: [-2, 4, 2], color: '#b0c0d0', intensity: 1.0 },
    toneMappingExposure: 1.1,
  },
  floor: {
    color: '#b0bec5',
    roughness: 0.3,
    metalness: 0.05,
    mirror: 0.4,
    blur: [600, 300],
    useTexture: false,
  },
  wallColor: '#c8d0d8',
  decorations: [
    {
      model: 'TreeA',
      count: 2,
      placement: 'cell-center',
      scaleMin: 0.8,
      scaleMax: 1.2,
      color: '#5a7a4a',
    },
    {
      model: 'RockA',
      count: 6,
      placement: 'scattered',
      scaleMin: 0.5,
      scaleMax: 1.0,
      color: '#7a8a90',
    },
    {
      model: 'RockB',
      count: 5,
      placement: 'scattered',
      scaleMin: 0.4,
      scaleMax: 0.9,
      color: '#6a7a80',
    },
    {
      model: 'BenchA',
      count: 3,
      placement: 'scattered',
      scaleMin: 0.7,
      scaleMax: 1.0,
      color: '#8a7060',
    },
  ],
  particles: {
    type: 'rain',
    color: '#a8cfe0',
    count: 220,
    speed: 9.0,
    opacity: 0.5,
  },
};

export const aiPresetAutumn: GalleryPreset = {
  id: 'autumn-forest',
  atmosphere: {
    type: 'sky',
    sunPosition: [4, 3, 8],
    turbidity: 12,
    rayleigh: 2.2,
    mieCoefficient: 0.006,
    mieDirectionalG: 0.82,
    clouds: true,
  },
  lighting: {
    hemisphere: ['#e8a050', '#6b4226', 0.8],
    ambient: { color: '#f0c070', intensity: 1.1 },
    directional: {
      position: [8, 6, 10],
      color: '#ffaa44',
      intensity: 1.6,
    },
    toneMappingExposure: 1.35,
  },
  floor: {
    color: '#8b5e3c',
    roughness: 0.85,
    metalness: 0.0,
    mirror: 0.0,
    blur: [200, 80],
    useTexture: true,
  },
  wallColor: '#d4a96a',
  decorations: [
    {
      model: 'TreeD',
      count: 2,
      placement: 'cell-center',
      scaleMin: 0.8,
      scaleMax: 1.2,
    },
    {
      model: 'TreeE',
      count: 2,
      placement: 'cell-center',
      scaleMin: 0.8,
      scaleMax: 1.1,
    },
    {
      model: 'RockA',
      count: 5,
      placement: 'scattered',
      scaleMin: 0.5,
      scaleMax: 1.0,
      color: '#7a6050',
    },
    {
      model: 'BenchA',
      count: 2,
      placement: 'scattered',
      scaleMin: 0.7,
      scaleMax: 0.9,
      color: '#7a4e28',
    },
  ],
  particles: {
    type: 'leaves',
    color: '#c0392b',
    count: 55,
    speed: 1.0,
    opacity: 0.88,
  },
};
