/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/present-a-round.glb -t -s -r public -o app/components/models/PresentARound.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['present-a-round_1']: THREE.Mesh;
    lid: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function PresentARound(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/present-a-round.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['present-a-round_1'].geometry}
        material={materials.colormap}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lid.geometry}
          material={materials.colormap}
          position={[0, 0.3, 0]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/GLBformat/present-a-round.glb');
