/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/tree-decorated-snow.glb -t -s -r public -o app/components/models/TreeDecoratedSnow.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['tree-decorated-snow_1']: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function TreeDecoratedSnow(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/tree-decorated-snow.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tree-decorated-snow_1'].geometry}
        material={materials.colormap}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/tree-decorated-snow.glb');
