/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/coralC.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/ucoralC.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    mesh1965416314: THREE.Mesh;
    mesh1965416314_1: THREE.Mesh;
  };
  materials: {
    mat20: THREE.MeshStandardMaterial;
    mat13: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function CoralC(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/coralC.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1965416314.geometry}
        material={materials.mat20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1965416314_1.geometry}
        material={materials.mat13}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/coralC.glb');
