/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/coralB.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/ucoralB.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    group1533979519: THREE.Mesh;
  };
  materials: {
    mat7: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function CoralB(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/coralB.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1533979519.geometry}
        material={materials.mat7}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/coralB.glb');
