/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/coralA.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/ucoralA.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    node_id63: THREE.Mesh;
  };
  materials: {
    Material_91: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function CoralA(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/coralA.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.node_id63.geometry}
        material={materials.Material_91}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/coralA.glb');
