/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/crystalA.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/ucrystalA.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    crystal_4: THREE.Mesh;
  };
  materials: {
    ['Material.004']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function CrystalA(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/crystalA.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.crystal_4.geometry}
        material={materials['Material.004']}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/crystalA.glb');
