/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/fishB.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/ufishB.tsx
*/

import * as THREE from 'three';
import React, { useEffect, useRef } from 'react';
import { useGraph } from '@react-three/fiber';
import { useAnimations, useGLTF } from '@react-three/drei';
import { GLTF, SkeletonUtils } from 'three-stdlib';

type ActionName = 'Armature|Swim';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    ClownFish_1: THREE.SkinnedMesh;
    ClownFish_2: THREE.SkinnedMesh;
    ClownFish_3: THREE.SkinnedMesh;
    Root: THREE.Bone;
  };
  materials: {
    Outline: THREE.MeshStandardMaterial;
    Body: THREE.MeshStandardMaterial;
    Stripes: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function FishB(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF('/GLBformat/basic/fishB.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions['Armature|Swim']?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group name="ClownFish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="ClownFish_1"
              geometry={nodes.ClownFish_1.geometry}
              material={materials.Outline}
              skeleton={nodes.ClownFish_1.skeleton}
              castShadow
              receiveShadow
            />
            <skinnedMesh
              name="ClownFish_2"
              geometry={nodes.ClownFish_2.geometry}
              material={materials.Body}
              skeleton={nodes.ClownFish_2.skeleton}
              castShadow
              receiveShadow
            />
            <skinnedMesh
              name="ClownFish_3"
              geometry={nodes.ClownFish_3.geometry}
              material={materials.Stripes}
              skeleton={nodes.ClownFish_3.skeleton}
              castShadow
              receiveShadow
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/fishB.glb');
