/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/flowerA.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/uflowerA.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    DesertMarigold_mesh: THREE.Mesh;
  };
  materials: {
    DesertMarigold_mat: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function FlowerA(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/flowerA.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DesertMarigold_mesh.geometry}
        material={materials.DesertMarigold_mat}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/flowerA.glb');
