/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/flowerPetal.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/FlowerPetal.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Petal_1: THREE.Mesh;
  };
  materials: {
    Flowers: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function FlowerPetal(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/flowerPetal.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Petal_1.geometry}
        material={materials.Flowers}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/flowerPetal.glb');
