/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/flowerC.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/uflowerC.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    group2033663355: THREE.Mesh;
    mesh790836088: THREE.Mesh;
    mesh790836088_1: THREE.Mesh;
    mesh790836088_2: THREE.Mesh;
    group1291483580: THREE.Mesh;
  };
  materials: {
    mat10: THREE.MeshStandardMaterial;
    mat21: THREE.MeshStandardMaterial;
    mat12: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function FlowerC(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/flowerC.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group2033663355.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1291483580.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh790836088.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh790836088_1.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh790836088_2.geometry}
        material={materials.mat12}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/flowerC.glb');
