/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/flowerTreeA.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/FlowerTreeA.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['Tree_green01_Cube007-Mesh']: THREE.Mesh;
    ['Tree_green01_Cube007-Mesh_1']: THREE.Mesh;
  };
  materials: {
    Wood_Tree01: THREE.MeshStandardMaterial;
    GreenLeaf_Tree01: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function FlowerTreeA(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/flowerTreeA.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Tree_green01_Cube007-Mesh'].geometry}
        material={materials.Wood_Tree01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Tree_green01_Cube007-Mesh_1'].geometry}
        material={materials.GreenLeaf_Tree01}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/flowerTreeA.glb');
