/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/flowerTreeB.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/FlowerTreeB.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['??????????_1']: THREE.Mesh;
    ['??????????_1_1']: THREE.Mesh;
  };
  materials: {
    ['??????']: THREE.MeshStandardMaterial;
    ['???????_??????']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function FlowerTreeB(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/flowerTreeB.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['??????????_1'].geometry}
        material={materials['??????']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['??????????_1_1'].geometry}
        material={materials['???????_??????']}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/flowerTreeB.glb');
