/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/flowerB.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/uflowerB.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    mesh1524081558: THREE.Mesh;
    mesh1524081558_1: THREE.Mesh;
    mesh1160013864: THREE.Mesh;
    mesh1160013864_1: THREE.Mesh;
    mesh1653023134: THREE.Mesh;
    mesh1653023134_1: THREE.Mesh;
    mesh1653023134_2: THREE.Mesh;
    mesh1741665748: THREE.Mesh;
    mesh1741665748_1: THREE.Mesh;
    mesh1741665748_2: THREE.Mesh;
    mesh605848671: THREE.Mesh;
    mesh605848671_1: THREE.Mesh;
    mesh605848671_2: THREE.Mesh;
    mesh875356185: THREE.Mesh;
    mesh875356185_1: THREE.Mesh;
    mesh1418125784: THREE.Mesh;
    mesh1418125784_1: THREE.Mesh;
    mesh1699578894: THREE.Mesh;
    mesh1699578894_1: THREE.Mesh;
    mesh2026508287: THREE.Mesh;
    mesh2026508287_1: THREE.Mesh;
    mesh2026508287_2: THREE.Mesh;
    mesh1869555222: THREE.Mesh;
    mesh1869555222_1: THREE.Mesh;
    mesh1869555222_2: THREE.Mesh;
    group305020849: THREE.Mesh;
    group1315161051: THREE.Mesh;
    mesh1336710718: THREE.Mesh;
    mesh1336710718_1: THREE.Mesh;
    mesh1336710718_2: THREE.Mesh;
    group1126844985: THREE.Mesh;
    mesh1662392388: THREE.Mesh;
    mesh1662392388_1: THREE.Mesh;
    mesh1662392388_2: THREE.Mesh;
    mesh1563464038: THREE.Mesh;
    mesh1563464038_1: THREE.Mesh;
    mesh1563464038_2: THREE.Mesh;
    mesh369730231: THREE.Mesh;
    mesh369730231_1: THREE.Mesh;
    mesh369730231_2: THREE.Mesh;
    mesh64326919: THREE.Mesh;
    mesh64326919_1: THREE.Mesh;
    mesh64326919_2: THREE.Mesh;
    group133156713: THREE.Mesh;
    group1548105374: THREE.Mesh;
    group1731819144: THREE.Mesh;
    mesh773970968: THREE.Mesh;
    mesh773970968_1: THREE.Mesh;
    mesh773970968_2: THREE.Mesh;
    mesh1513215620: THREE.Mesh;
    mesh1513215620_1: THREE.Mesh;
    mesh1548443602: THREE.Mesh;
    mesh1548443602_1: THREE.Mesh;
    mesh371625766: THREE.Mesh;
    mesh371625766_1: THREE.Mesh;
    mesh371625766_2: THREE.Mesh;
    group574375989: THREE.Mesh;
    group340541725: THREE.Mesh;
    group528986637: THREE.Mesh;
    mesh201291130: THREE.Mesh;
    mesh201291130_1: THREE.Mesh;
    mesh201291130_2: THREE.Mesh;
    mesh647133167: THREE.Mesh;
    mesh647133167_1: THREE.Mesh;
    mesh647133167_2: THREE.Mesh;
    group743581695: THREE.Mesh;
    mesh1089069114: THREE.Mesh;
    mesh1089069114_1: THREE.Mesh;
    mesh1089069114_2: THREE.Mesh;
    group1051964877: THREE.Mesh;
    mesh851135502: THREE.Mesh;
    mesh851135502_1: THREE.Mesh;
    mesh851135502_2: THREE.Mesh;
    group1517434150: THREE.Mesh;
    mesh1294012767: THREE.Mesh;
    mesh1294012767_1: THREE.Mesh;
    mesh1294012767_2: THREE.Mesh;
    mesh1195982837: THREE.Mesh;
    mesh1195982837_1: THREE.Mesh;
    mesh1195982837_2: THREE.Mesh;
    group25708318: THREE.Mesh;
    group1376070046: THREE.Mesh;
    mesh1219209497: THREE.Mesh;
    mesh1219209497_1: THREE.Mesh;
    mesh1219209497_2: THREE.Mesh;
    group1204995636: THREE.Mesh;
    mesh1035713103: THREE.Mesh;
    mesh1035713103_1: THREE.Mesh;
    mesh1035713103_2: THREE.Mesh;
    mesh797648510: THREE.Mesh;
    mesh797648510_1: THREE.Mesh;
    mesh478565310: THREE.Mesh;
    mesh478565310_1: THREE.Mesh;
    mesh478565310_2: THREE.Mesh;
    mesh445126197: THREE.Mesh;
    mesh445126197_1: THREE.Mesh;
    mesh445126197_2: THREE.Mesh;
    mesh1367787382: THREE.Mesh;
    mesh1367787382_1: THREE.Mesh;
    mesh1587333848: THREE.Mesh;
    mesh1587333848_1: THREE.Mesh;
    mesh1587333848_2: THREE.Mesh;
    mesh472026721: THREE.Mesh;
    mesh472026721_1: THREE.Mesh;
    mesh472026721_2: THREE.Mesh;
    mesh472026721_3: THREE.Mesh;
    mesh941805466: THREE.Mesh;
    mesh941805466_1: THREE.Mesh;
    mesh941805466_2: THREE.Mesh;
    mesh941805466_3: THREE.Mesh;
    mesh1199946381: THREE.Mesh;
    mesh1199946381_1: THREE.Mesh;
    mesh1199946381_2: THREE.Mesh;
    mesh1199946381_3: THREE.Mesh;
  };
  materials: {
    mat11: THREE.MeshStandardMaterial;
    mat10: THREE.MeshStandardMaterial;
    mat9: THREE.MeshStandardMaterial;
    mat7: THREE.MeshStandardMaterial;
    mat0: THREE.MeshStandardMaterial;
    mat1: THREE.MeshStandardMaterial;
    mat6: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function FlowerB(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/flowerB.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group305020849.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1315161051.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1126844985.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group133156713.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1548105374.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1731819144.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group574375989.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group340541725.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group528986637.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group743581695.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1051964877.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1517434150.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group25708318.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1376070046.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1204995636.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1524081558.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1524081558_1.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1160013864.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1160013864_1.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1653023134.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1653023134_1.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1653023134_2.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1741665748.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1741665748_1.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1741665748_2.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh605848671.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh605848671_1.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh605848671_2.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh875356185.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh875356185_1.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1418125784.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1418125784_1.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1699578894.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1699578894_1.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh2026508287.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh2026508287_1.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh2026508287_2.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1869555222.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1869555222_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1869555222_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1336710718.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1336710718_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1336710718_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1662392388.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1662392388_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1662392388_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1563464038.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1563464038_1.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1563464038_2.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh369730231.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh369730231_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh369730231_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64326919.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64326919_1.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64326919_2.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh773970968.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh773970968_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh773970968_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1513215620.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1513215620_1.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1548443602.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1548443602_1.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh371625766.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh371625766_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh371625766_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh201291130.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh201291130_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh201291130_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh647133167.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh647133167_1.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh647133167_2.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1089069114.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1089069114_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1089069114_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh851135502.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh851135502_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh851135502_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1294012767.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1294012767_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1294012767_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1195982837.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1195982837_1.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1195982837_2.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1219209497.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1219209497_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1219209497_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1035713103.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1035713103_1.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1035713103_2.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh797648510.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh797648510_1.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh478565310.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh478565310_1.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh478565310_2.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh445126197.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh445126197_1.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh445126197_2.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1367787382.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1367787382_1.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1587333848.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1587333848_1.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1587333848_2.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh472026721.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh472026721_1.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh472026721_2.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh472026721_3.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh941805466.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh941805466_1.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh941805466_2.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh941805466_3.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1199946381.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1199946381_1.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1199946381_2.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1199946381_3.geometry}
        material={materials.mat1}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/flowerB.glb');
