/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/rocketB.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/urocketB.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['Node-Mesh']: THREE.Mesh;
    ['Node-Mesh_1']: THREE.Mesh;
    ['Node-Mesh_2']: THREE.Mesh;
    ['Node-Mesh_3']: THREE.Mesh;
    ['Node-Mesh_4']: THREE.Mesh;
    ['Node-Mesh_5']: THREE.Mesh;
    ['Node-Mesh_6']: THREE.Mesh;
  };
  materials: {
    mat21: THREE.MeshStandardMaterial;
    mat20: THREE.MeshStandardMaterial;
    mat8: THREE.MeshStandardMaterial;
    mat3: THREE.MeshStandardMaterial;
    mat13: THREE.MeshStandardMaterial;
    mat12: THREE.MeshStandardMaterial;
    mat14: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function RocketB(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/rocketB.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh'].geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_1'].geometry}
        material={materials.mat20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_2'].geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_3'].geometry}
        material={materials.mat3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_4'].geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_5'].geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_6'].geometry}
        material={materials.mat14}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/rocketB.glb');
