/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/starfish.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/Starfish.tsx
Author: ender7396 (https://sketchfab.com/ender7396)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/starfish-3e4ffd35592645919311bfdd18b84b56
Title: StarFish
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['StarFish_01_-_Default_0']: THREE.Mesh;
  };
  materials: {
    ['01_-_Default']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Starfish(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/starfish.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['StarFish_01_-_Default_0'].geometry}
          material={materials['01_-_Default']}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[1.801, 1.801, 1]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/starfish.glb');
