/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GLBformat/basic/starA.glb -t -s -r public -o src/components/exhibition-gallery/models/basic/ustarA.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Star: THREE.Mesh;
  };
  materials: {
    star: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function StarA(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/GLBformat/basic/starA.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Star.geometry}
        material={materials.star}
        position={[0, 0.549, 0]}
        rotation={[0, 0, -Math.PI]}
        scale={40}
      />
    </group>
  );
}

useGLTF.preload('/GLBformat/basic/starA.glb');
