import { Artwork } from './Types';

export const MOCK_ARTWORKS: Artwork[] = [
  {
    id: '1',
    title: '무지개 마을',
    artist: '송하윤',
    description:
      '비 온 뒤 뜨는 무지개처럼 아름다운 마을을 그렸어요. 모든 집이 무지개 색깔로 칠해져 있어요.',
    exhibitionTitle: '꿈꾸는 아이들',
    academyName: '해피아트 미술학원',
    imageUrl: '/gallery/painting.png',
    likesCount: 22,
    createdAt: '2025-04-12',
  },
  {
    id: '2',
    title: '하늘을 나는 꿈',
    artist: '김지호',
    description: '하늘 높이 날고 싶은 꿈을 그림으로 담았어요.',
    exhibitionTitle: '꿈꾸는 아이들',
    academyName: '해피아트 미술학원',
    imageUrl: '/images/sample_thumb.png',
    likesCount: 15,
    createdAt: '2025-04-10',
  },
  {
    id: '3',
    title: '나의 반려묘 나비',
    artist: '이소율',
    description:
      '우리 집 고양이 나비를 그렸어요. 나비는 항상 창가에 앉아 있어요.',
    exhibitionTitle: '나의 세계 – 상상화전',
    academyName: '해피아트 미술학원',
    imageUrl: '/gallery/painting.png',
    likesCount: 35,
    createdAt: '2025-04-08',
  },
  {
    id: '4',
    title: '도시의 밤',
    artist: '박준서',
    description: '밤에 빛나는 도시의 야경을 수채화로 표현했어요.',
    exhibitionTitle: '나의 세계 – 상상화전',
    academyName: '해피아트 미술학원',
    imageUrl: '/images/sample_thumb.png',
    likesCount: 27,
    createdAt: '2025-04-06',
  },
  {
    id: '5',
    title: '상상의 숲',
    artist: '최아린',
    description:
      '제가 꿈에서 본 마법의 숲을 그렸어요. 나무마다 꽃이 피어 있어요.',
    exhibitionTitle: '나의 세계 – 상상화전',
    academyName: '해피아트 미술학원',
    imageUrl: '/gallery/painting.png',
    likesCount: 42,
    createdAt: '2025-04-04',
  },
  {
    id: '6',
    title: '우리 가족',
    artist: '정하은',
    description: '사랑하는 우리 가족을 그렸어요. 엄마, 아빠, 나, 강아지까지!',
    exhibitionTitle: '봄의 소리전',
    academyName: '해피아트 미술학원',
    imageUrl: '/images/sample_thumb.png',
    likesCount: 18,
    createdAt: '2025-03-30',
  },
  {
    id: '7',
    title: '바다의 노래',
    artist: '윤시우',
    description: '파도 소리를 들으며 그린 바다 그림이에요.',
    exhibitionTitle: '봄의 소리전',
    academyName: '해피아트 미술학원',
    imageUrl: '/gallery/painting.png',
    likesCount: 31,
    createdAt: '2025-03-25',
  },
  {
    id: '8',
    title: '봄날의 꿈',
    artist: '강민준',
    description: '봄이 되면 꽃들이 피어나는 것처럼 제 꿈도 활짝 피어날 거예요.',
    exhibitionTitle: '봄의 소리전',
    academyName: '해피아트 미술학원',
    imageUrl: '/images/sample_thumb.png',
    likesCount: 24,
    createdAt: '2025-03-20',
  },
];
